[package]
name = "dfs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
tonic = "0.12.3"
prost = "0.13.3"

[build-dependencies]
tonic-build = "0.12.3"